language: objective-c
xcode_project: ArrayLoader.xcodeproj
xcode_scheme: ArrayLoader-OSX
osx_image: xcode8.0
before_install: true
install: true
git:
  submodules: false
script:
  - /usr/local/bin/brew update
  - /usr/local/bin/brew install carthage
  - /usr/local/bin/carthage bootstrap --platform Mac
  - xctool -project ArrayLoader.xcodeproj -scheme ArrayLoader-OSX
  - xcodebuild test -project ArrayLoader.xcodeproj -scheme ArrayLoader-OSX
