language: objective-c
xcode_project: ArrayLoader.xcodeproj
xcode_scheme: ArrayLoader-OSX
osx_image: xcode8
before_install: true
install: true
git:
  submodules: false
script:
  - /usr/local/bin/carthage bootstrap --platform Mac --no-use-binaries
  - xcodebuild -project ArrayLoader.xcodeproj -scheme ArrayLoader-OSX
  - xcodebuild test -project ArrayLoader.xcodeproj -scheme ArrayLoader-OSX
